on:
  change:
    - "**/*.go"
    - go.mod
    - go.sum
    - .golangci.yml
    - Makefile
    - flake.nix
    - flake.lock
    - .watch.yaml
  ignore:
    - ".git/**"
    - ".tmp/**"
    - .watch.sock
  socket: .watch.sock
  respect_gitignore: true

execution:
  concurrency: 6
  output: show-on-failure
  timeout: 5m
  recovery_policy: skip

jobs:
  - name: nixfmt
    run_on_init: true
    parallel: checks
    run: nix develop -c nixfmt --check flake.nix
  - name: flake-check
    run_on_init: true
    parallel: checks
    run: nix develop -c nix flake check
  - name: fzz-check
    run_on_init: true
    parallel: checks
    run: nix develop -c fzz check
  - name: go-build
    run_on_init: true
    parallel: checks
    run: nix develop -c go build ./...
  - name: lint
    run_on_init: true
    parallel: checks
    run: nix develop -c golangci-lint run
  - name: go-test
    run_on_init: true
    parallel: checks
    run: nix develop -c go test ./...
  - name: install-cli
    run_on_init: true
    run: nix develop -c go install ./cmd/gev
